
package com.invertir;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaSoap", targetNamespace = "http://invertir.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaSoap {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     * @throws NombreInexistenteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "provocarError", targetNamespace = "http://invertir.com/", className = "com.invertir.ProvocarError")
    @ResponseWrapper(localName = "provocarErrorResponse", targetNamespace = "http://invertir.com/", className = "com.invertir.ProvocarErrorResponse")
    @Action(input = "http://invertir.com/ConsultaSoap/provocarErrorRequest", output = "http://invertir.com/ConsultaSoap/provocarErrorResponse", fault = {
        @FaultAction(className = NombreInexistenteException_Exception.class, value = "http://invertir.com/ConsultaSoap/provocarError/Fault/NombreInexistenteException")
    })
    public String provocarError(
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws NombreInexistenteException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.invertir.Cotizacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCotizaciones", targetNamespace = "http://invertir.com/", className = "com.invertir.ObtenerCotizaciones")
    @ResponseWrapper(localName = "obtenerCotizacionesResponse", targetNamespace = "http://invertir.com/", className = "com.invertir.ObtenerCotizacionesResponse")
    @Action(input = "http://invertir.com/ConsultaSoap/obtenerCotizacionesRequest", output = "http://invertir.com/ConsultaSoap/obtenerCotizacionesResponse")
    public List<Cotizacion> obtenerCotizaciones();

    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hola")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Hola", targetNamespace = "http://invertir.com/", className = "com.invertir.Hola")
    @ResponseWrapper(localName = "HolaResponse", targetNamespace = "http://invertir.com/", className = "com.invertir.HolaResponse")
    @Action(input = "http://invertir.com/ConsultaSoap/HolaRequest", output = "http://invertir.com/ConsultaSoap/HolaResponse")
    public String hola(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

}
