
package com.invertir;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaSoap", targetNamespace = "http://invertir.com/", wsdlLocation = "http://localhost:8080/ejemplo2/saludar?wsdl")
public class ConsultaSoap_Service
    extends Service
{

    private final static URL CONSULTASOAP_WSDL_LOCATION;
    private final static WebServiceException CONSULTASOAP_EXCEPTION;
    private final static QName CONSULTASOAP_QNAME = new QName("http://invertir.com/", "ConsultaSoap");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ejemplo2/saludar?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTASOAP_WSDL_LOCATION = url;
        CONSULTASOAP_EXCEPTION = e;
    }

    public ConsultaSoap_Service() {
        super(__getWsdlLocation(), CONSULTASOAP_QNAME);
    }

    public ConsultaSoap_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTASOAP_QNAME, features);
    }

    public ConsultaSoap_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTASOAP_QNAME);
    }

    public ConsultaSoap_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTASOAP_QNAME, features);
    }

    public ConsultaSoap_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaSoap_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaSoap
     */
    @WebEndpoint(name = "ConsultaSoapPort")
    public ConsultaSoap getConsultaSoapPort() {
        return super.getPort(new QName("http://invertir.com/", "ConsultaSoapPort"), ConsultaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaSoap
     */
    @WebEndpoint(name = "ConsultaSoapPort")
    public ConsultaSoap getConsultaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://invertir.com/", "ConsultaSoapPort"), ConsultaSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTASOAP_EXCEPTION!= null) {
            throw CONSULTASOAP_EXCEPTION;
        }
        return CONSULTASOAP_WSDL_LOCATION;
    }

}
